#!/bin/bash

# Define variables
WEBSERVER="apache2"  # Change to "nginx" if using Nginx
DB_USER="your_db_user"
DB_PASSWORD="your_db_password"
DB_NAME="wordpress_db"
WP_USER="admin"
WP_PASSWORD="your_wp_password"
WP_EMAIL="admin@example.com"

# Update and install necessary packages
sudo apt-get update
sudo apt-get install -y $WEBSERVER mysql-server php php-mysql php-curl php-gd php-mbstring php-xml unzip

# Download and extract WordPress
wget https://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz
sudo cp -R wordpress/* /var/www/html/
sudo chown -R www-data:www-data /var/www/html/

# Configure the database
sudo mysql -u root <<MYSQL_SCRIPT
CREATE DATABASE $DB_NAME;
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
EXIT;
MYSQL_SCRIPT

# Configure WordPress
cd /var/www/html/
cp wp-config-sample.php wp-config.php
sed -i "s/database_name_here/$DB_NAME/" wp-config.php
sed -i "s/username_here/$DB_USER/" wp-config.php
sed -i "s/password_here/$DB_PASSWORD/" wp-config.php

# Set up WordPress constants
echo "define('FS_METHOD', 'direct');" >> wp-config.php
echo "define('WP_HOME','http://your_domain_or_ip');" >> wp-config.php
echo "define('WP_SITEURL','http://your_domain_or_ip');" >> wp-config.php

# Set up WordPress admin user
echo "INSERT INTO wp_users (user_login, user_pass, user_email) VALUES ('$WP_USER', MD5('$WP_PASSWORD'), '$WP_EMAIL');" | sudo mysql -u root $DB_NAME
echo "INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES (1, 'wp_capabilities', 'a:1:{s:13:\"administrator\";s:1:\"1\";}');" | sudo mysql -u root $DB_NAME
echo "INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES (1, 'wp_user_level', '10');" | sudo mysql -u root $DB_NAME

# Restart the web server
sudo service $WEBSERVER restart

echo "WordPress has been successfully installed and configured. Visit http://your_domain_or_ip to access your site."
