all:
  hosts:
    web01:
      ansible_host: <IP>
      ansible_user: ec2-user
      ansible_ssh_private_key_file: control.pem
    db01:
      ansible_host: <IP>
  children:
    webservers:
      hosts:
        web01:
    dbservers:
      hosts:
         db01:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: control.pem
